theme: jekyll-theme-midnight

title: Philippe Morier
description: Place to keep things.

collections_dir: collections
collections:
  flash_cards:
    output: true

defaults:
  - scope:
      path: ''
      type: 'flash_cards'
    values:
      layout: flash_card
