theme: jekyll-theme-midnight

title: Philippe Morier
description: Place to keep things.

#paginate: 10

collections_dir: collections
collections:
  flash_cards:
    output: true

defaults:
  - scope:
      path: 'collections/_flash_cards'
      type: 'flash_cards'
    values:
      layout: flash_card
